### ISSUE TITLE
start and stop charge?

### ISSUE THREAD

**Issue by rchiileea** [Hyundai-Kia-Connect/hyundai_kia_connect_api#375] opened 2023-08-02 14:28 UTC
* Hyundai / Kia Connect version:
* Python version:
* Operating System:

### Description

just wondering if we will ever see start and stop charge buttons appear

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by cdnninja** [comment] 2023-08-02 14:40
This is an API.  I assume you mean on the home assistant part of this?  If so the service already exists and has for some time. Would be straightforward for you to add this to your dashboard if you so desire.

**Comment by rchiileea** [comment] 2023-08-02 18:21
Oh I tried that via the Hyundai Kia connect and call device it fails.

**Comment by cdnninja** [comment] 2023-08-02 19:21
So you don't have an issue with creating a button but rather the service itself? I see you posted separately to the home assistant repo so thinking we continue there?

**Comment by rchiileea** [comment] 2023-08-03 10:57
I posted a reply there, I can do service calls, but need to reload the integration after every single call, so basically

call service unlock, car unlocks- call service car lock, erros, but if I do call service unlock, reload integration then call service lock its fine (if I attempt to run another call service after one has run it errors, I have to reload the automation to do any call service again).

**Comment by agx** [comment] 2023-10-09 11:29
> I posted a reply there, I can do service calls, but need to reload the integration after every single call, so basically
> 
> call service unlock, car unlocks- call service car lock, erros, but if I do call service unlock, reload integration then call service lock its fine (if I attempt to run another call service after one has run it errors, I have to reload the integration to do any call service again).

This looks like the same issue as #424 ? See the workaround there about setting the token to `None`. If se we could close this as #424 has a minimal reproducer.

**Comment by fuatakgun** [comment] 2023-10-09 11:54
One thing to consider with excessive logins, i got locked out for one day because of this, so use it cautiously.

I was heavily testing under the development environment and logged in multiple times. Didn't remember the exact number

**Comment by cdnninja** [comment] 2023-11-10 20:00
This is duplicate of a few others by the sounds of it. Closing out.

**Closed by cdnninja** 2023-11-10 20:00 UTC
